config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'categories#index'

  resources :categories, only: [:index, :show, :edit, :update] do
    resources :questions, only: [:new, :create, :edit, :update]
  end

  resources :questions, only: [:new, :show, :edit, :update, :destroy] do
    resources :answers, except: [:index, :show]
    resources :symbols
  end

  resources :answers do
    member do
      put "like", to: "answers#upvote"
      put "dislike", to: "answers#downvote"
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  acts_as_votable

  belongs_to :question
  belongs_to :user

  validates :content, presence: true
  validates :user, presence: true
  validates :question, presence: true

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :questions
  has_many :chords

  validates :name, presence: true, uniqueness: true

end

app/models/question.rb
class Question < ActiveRecord::Base

  mount_uploader :score, ScoreUploader
  mount_uploader :audio, AudioUploader

  has_many :answers
  has_many :symbols

  belongs_to :user
  belongs_to :category

  validates :title, presence: true
  validates :description, presence: true
  validates :user, presence: true
  validates :category, presence: true
end

app/models/symbol.rb
class Symbol < ActiveRecord::Base
  belongs_to :question

  validates :question, presence: true
  validates :name, presence: true
  validates :left, presence: true
  validates :top, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :questions
  has_many :answers

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :json

  def new
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    @answer = current_user.answers.find(params[:id])
  end

  def update
    @answer = current_user.answers.find(params[:id])
    @question = @answer.question
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to(@answer) }
        format.json { render json: @answer }
      end
    end
  end

  def destroy
    @answer = current_user.answers.find(params[:id])
    @question = @answer.question

    if @answer.destroy
      flash[:notice] = "Your answer was deleted!"
    else
      flash[:notice] = "Answer not deleted"
    end
    redirect_to question_path(@question)
  end

  def upvote
    @answer = Answer.find(params[:id])
    @answer.upvote_by current_user
    @question = @answer.question
    redirect_to question_path(@question)
  end

  def downvote
    @answer = Answer.find(params[:id])
    @answer.downvote_by current_user
    @question = @answer.question
    redirect_to question_path(@question)
  end
  
  private

  def answer_params
    params.require(:answer).permit(:content, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @questions = @category.questions
    @question = Question.new
    @categories = Category.where.not(id: @category.id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @question = Question.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @question = Question.new
  end

  def create
    @category = Category.find(params[:category_id])
    @question = Question.new(question_params)
    @question.category = @category
    @question.user = current_user

    if @question.save
      flash[:notice] = "Question added!"
      redirect_to category_path(@question.category)
    else
      flash[:notice] = "Question not added."
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to category_path(@question.category)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:notice] = "Question deleted!"
    else
      flash[:notice] = "You must be logged in to do that!"
    end
    redirect_to category_path(@question.category)
  end

  private

  def question_params
    params.require(:question).permit(:title, :description, :audio)
  end
end

app/controllers/symbols_controller.rb
class SymbolsController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  respond_to :js

  def create
    respond_to do |format|
      format.js do
        @question = Question.find(params[:question_id])
        @symbol = @question.symbols.create(symbol_params)
      end
    end
  end

  def update
    respond_to do |format|
      format.js do
        @question = Question.find(params[:question_id])
        @symbol = Symbol.find(params[:id])
        @symbol.update(symbol_params)
      end
    end
  end

  private

  def symbol_params
    params.require(:symbol).permit(:name, :top, :left, :question_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  private

  def user_params
    params.require(:user).permit(:email, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
<% if @answer.errors.any? %>
<div id="error_explanation">
  <h2 class="formerrors"><%= pluralize(@answer.errors.count, "error") %> prohibited this review from being saved:</h2>
  <ul>
    <% @answer.errors.full_messages.each do |message| %>
    <li class="formerrors"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div id="answer-content">
  <%= f.text_area :content %>
</div>

<div id="answer-button">
  <%= f.submit "Theorize!", class: "button small radius", id: "answer_button" %>
</div>

<% end %>

app/views/categories/index.html.erb
<body class="home">
  <div class="circle-container">
    <div>
      <% @categories.each do |category| %>
        <div class="category-name"><%= link_to category.name, category_path(category) %></div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <h6 id="title-1">Theoretically</h6>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <h6></h6>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns" id="logo">
      <%= image_tag("clef.png", :class => "fadeIn fadeIn-3s fadeIn-Delay-3s") %>
    </div>
  </div>

  <div class="large-12 columns">
    <h6 id="title-2">Speaking</h6>
    <h6 id="sub-title">Your hub for all things music theory.</h6>
  </div>
</body>

app/views/categories/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <ul class="inline-list">
      <li><h1 class="name"><%= @category.name %></h1></li>
      <li><input id="question-new" type="button" value="New Question" method="GET"></li>
      <li id="curvy-staff"><%= image_tag("curvystaff.jpg") %></li>
    </ul>
  </div>
</div>

<div id="form">
  <%= render "questions/form" %>
</div>

<%= render "questions/index" %>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TSpeaking</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>

  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
  </body>

  <footer>
    <nav class="top-bar">
      <section class="top-bar-section">
        <ul class="right">
          <%- if current_user -%>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
            <li class="name"><a href="/">Home</a></li>
          <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li><a href="/">Home</a></li>
          <%- end -%>
        </ul>
      </section>
    </nav>
  </footer>
</html>

app/views/questions/_form.html.erb
<%= form_for [@category, @question] do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2 class="formerrors"><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li class="formerrors"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <div class="row">
        <div class="large-6 columns">
          <div class="row">
            <div class="small-2 columns">
            </div>
            <div class="small-10 columns">
              <%= f.text_field :title, id: "title-field", placeholder: "Title" %><br>
              <%= f.text_area :description, id: "description-field", placeholder: "Description" %><br>
            </div>
          </div>
        </div>
        <div class="large-6 columns">
          <div class="row">
            <div class="small-2 columns">
            </div>
            <div class="small-10 columns">
              <div class="small-6 columns">
                <%= f.label :audio, for: "audio-field", class: "audio-label" %><br>
              </div>
              <div class="small-6 columns">
                <%= f.file_field :audio, id: "audio-field" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="small-2 columns">
            </div>
            <div class="small-10 columns">
              <div class="small-6 columns">
                <%= f.label :score, for: "score-field", class: "score-label" %><br>
              </div>
              <div class="small-6 columns">
                <%= f.file_field :score, id: "score-field" %>
              </div>
                <%= f.submit "Add Question", id: "submit-button", class: "button small radius" %>
            </div>
          </div>
        </div>
      </div>
        <div class="large-5 columns">
          <div class="row">
            <div class="small-6 columns">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/questions/_index.html.erb
<div class="row">
  <div class="large-3 columns">
    <div id="other_categories">
      <% @categories.each do |category| %>
      <ul id="list">
        <div id="category-list"><%= link_to category.name, category_path(category) %></div>
      </ul>
      <% end %>
    </div>
  </div>

  <div class="large-7 columns" id="box">
    <% @questions.each do |question| %>
      <div class="large-2 columns small-3"><%= image_tag("bass.png") %></div>
        <div class="large-10 columns" id="questions">
          <p><strong><%= link_to question.title, question_path(question) %></strong></p>
          <% if question.user.username == nil %>
            <div id="no-username">asked by anonymous on <%= question.user.created_at.to_s.gsub(/[UTC]/, '') %></div>
          <% else %>
            <div id="username">asked by <%= question.user.username %> on <%= question.user.created_at.to_s.gsub(/[UTC]/, '') %></div>
          <% end %>
          <ul class="inline-list">
            <li><%= link_to "edit", edit_question_path(question) %></li>
            <li><%= link_to "delete", question_path(question), method: :delete %></li>
          </ul>
        </div>
        <hr/>
      <% end %>
    </div>
    <hr/>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render "form" %>

app/views/questions/new.html.erb
<%= render "form" %>

app/views/questions/show.html.erb
<div class="row">
  <div class="large-12 columns" id="question-title">
    <h3><%= @question.title %></h3><br>
  </div>
</div>

<div class="row">
  <div class="large-12 columns" id="question-description">
    <h6><%= @question.description %></h6>
  </div>
</div>

<div class="row">
  <div class="large-6 columns">
    <a class="lightbox" href="<%= @question.score %>" data-lightbox="clef">
      <img id="score" src="<%= @question.score %>" />
    </a>
  </div>

  <div class="large-6 columns">
    <audio controls>
      <source src="<%= @question.audio %>">
    </audio>
  </div>
</div>

<div class="row">
  <div class="large-12 columns" id="staff">
    <%= image_tag("blankstaff.jpg") %>
  </div>
</div>

<div class="row">
  <p id="instructions">Drag and drop a symbol onto the staff! To remove, simply double click. </p>
</div>

<div class="row">
  <div class="all-symbols">
    <div class="symbols" id="quarter">&#9833;</div>
    <div class="symbols" id="eighth">&#9834;</div>
    <div class="symbols" id="flat">&#9837;</div>
    <div class="symbols" id="sharp">&#9839;</div>
    <div class="symbols" id="natural">&#9838;</div>
    <div class="symbols" id="g-clef">&#119070;</div>
    <div class="symbols" id="bass-clef">&#119074;</div>
  </div>
</div>

<div class="row">
  <div class="large-12 columns" id="answer-form">
    <%= render "answers/form" %>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
      <div class="answers">
        <% @question.answers.each do |answer| %>
          <div>
            <div id="sharp2"><%= link_to image_tag("sharp.gif"), like_answer_path(answer), method: :put %></div>
              <%= answer.score %>
              <%= best_in_place answer, :content, type: :textarea %> <span><%= link_to "delete", answer_path(answer), method: :delete %><span>
            <div id="flat2"><%= link_to image_tag("flat.png"), dislike_answer_path(answer), method: :put %></div>
            <% if answer.user.username == nil %>
              <div id="no-useranswer">theorized by anonymous on <%= answer.user.created_at.to_s.gsub(/[UTC]/, '') %></div>
            <% else %>
              <div id="useranswer">theorized by <%= answer.user.username %> on <%= answer.user.created_at.to_s.gsub(/[UTC]/, '') %></div>
            <% end %>
            <hr/>
          </div>
        <% end %>
      </div>
  </div>
</div>

<div id="question-id"><%= @question.id %></div>